baseURL = 'https://brianflynn.org/'
languageCode = 'en-us'
title = 'Brian Flynn'
theme = 'brian'

[menu]

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10

[[menu.main]]
  name = 'Blog'
  url = '/blog'
  weight = 20

[[menu.main]]
  name = 'Tech'
  url = '/tech'
  weight = 30

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 40

[params]
  favicon = "images/favicon.ico"
  logo = "/images/bn.png"
  categories = ["Personal News","Reviews","Technology","Website Updates"]  
